#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Android.Content;
using MrelsApp.Droid.Renderers;
using Xamarin.Forms;

[assembly: ExportRenderer(typeof(Button), typeof(CustomButtonRenderer))]
namespace MrelsApp.Droid.Renderers
{
    class CustomButtonRenderer : Xamarin.Forms.Platform.Android.ButtonRenderer
    {
        public CustomButtonRenderer(Context context) : base(context)
        {

        }
    }
}